### ISSUE TITLE
Compiling with NFFT 3.2.4

### ISSUE THREAD

**Issue by Maderthaner** [FilipeMaia/spsim#5]
Hi,

I just tried to compile spsim with NFFT and run into errors in src/diffraction.c 

There are a few typos where it says 'nnfft_*' that likely should read 'nfft_*'.

However, I corrected those on my source but I run into new errors:
/Users/Max/spsim/src/diffraction.c:613:4: error: no member named 'v' in 'nfft_plan'
        p.v[k*3]   =  HKL_list[k*3]/max_v[0];
        ~ ^
/Users/Max/spsim/src/diffraction.c:614:4: error: no member named 'v' in 'nfft_plan'
        p.v[k*3+1] =  HKL_list[k*3+1]/max_v[1];
        ~ ^
/Users/Max/spsim/src/diffraction.c:615:4: error: no member named 'v' in 'nfft_plan'
        p.v[k*3+2] =  HKL_list[k*3+2]/max_v[2];

Those, I don't really can make out.

PS: it does compile without nfft...

**Comment by FilipeMaia** [comment]
Hi,

Hi Max,

nnfft is correct, that's one of the variants. You have to explicitly enable it during compilation (--enable-nnfft or --enable-all).
A better alternative is to use https://github.com/mhantke/condor, which is where spsim has now been integrated, but you'll still need an nnfft enabled nfft library.

 If you just want to do a quick simulation you can even use the online interface http://lmb.icm.uu.se/condor/simulation/

**Comment by mhantke** [comment]
Hi Max,

could you please paste in your configuration file and your errors that you got before you edited your source? Thanks!

Cheers,
the other Max.

**Comment by Maderthaner** [comment]
Hello you two,

thanks for the fast reply.

I thought about nnfft being a proper command but was surprised it didn't find it. My error **was**:
```
[ 10%] Building C object src/CMakeFiles/_spsim_pybackend.dir/diffraction.c.o
/Users/Max/spsim/src/diffraction.c:523:3: error: unknown type name 'nnfft_plan'; did you
      mean 'nfft_plan'?
  nnfft_plan p;
  ^~~~~~~~~~
  nfft_plan
```

I recompiled nffft with --enable-all and then enabled it in spsim again and it did compile this time.
I was (blindly) following [http://lmb.icm.uu.se/condor/static/docs/installation.html#b-nfft](http://lmb.icm.uu.se/condor/static/docs/installation.html#b-nfft). Maybe one could change the line into `./configure --enable-all`

Other than that owl and condor aren't really in harmony with my brewed python and I'm hesitant reverting back. So, mostly I was just 'playing' around and see what I can get compiled.

Thanks again and best regards from Chicagoland,
Max
