### ISSUE TITLE
Wrong element retrieval from PDB

### ISSUE THREAD

**Issue by mhantke** [FilipeMaia/spsim#7]
When using the function get_Molecule_from_pdb for PDB entry 1GRO the function wrongly identifies some Hydrogens for Heliums. We are using the atom entry (columns 13-16). These can be modified and element assignment may be ambiguous. I suggest to use the information of the element entry (columns 77-78) instead.

**Comment by FilipeMaia** [comment]
I think one has to be careful. Are you sure that "all" PDBs define the element entry in columns 77-78?

**Comment by mhantke** [comment]
This is the way it is defined here:
http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

**Comment by mhantke** [comment]
Maybe it's time to write a validation routine that checks a couple of PDBs...?

**Comment by FilipeMaia** [comment]
I looked through some random PDBs and they all seem to have the element column so it's probably ok.
